linters:
  enable-all: true
  exclude-use-default: false
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - ireturn
    - maligned
    - paralleltest
    - scopelint
    - varnamelen

run:
  tests: false

issues:
  exclude-use-default: false
  exclude:
    - 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked'

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    exclude-functions:
      - '(io.Closer).Close'
  varnamelen:
    ignore-decls:
      - 'w http.ResponseWriter'
      - 'r *http.Request'
      - 'ts time.Time'
