env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  - id: jwt-auth-proxy
    main: ./cmd/jwt-auth-proxy
    binary: jwt-auth-proxy
    flags:
      - -tags=release
      - -buildmode=default
      - -trimpath
      - -v
    mod_timestamp: '{{ .CommitTimestamp }}'
    goarm: [5, 7]
    goos: ['linux', 'darwin', 'windows']
    goarch: ['amd64', 'arm', 'arm64']

archives:

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
    - "ghcr.io/na4ma4/jwt-auth-proxy:{{ .Tag }}"
    - "ghcr.io/na4ma4/jwt-auth-proxy:{{ .Major }}"
    - "ghcr.io/na4ma4/jwt-auth-proxy:latest"
    extra_files:
    - "scripts/replace-links-in-ssl-certs.sh"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

nfpms:
  -
    id: jwt-auth-proxy
    package_name: jwt-auth-proxy
    file_name_template: "jwt-auth-proxy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - jwt-auth-proxy
    homepage: https://github.com/na4ma4/jwt-auth-proxy
    maintainer: na4ma4 <na4ma4@users.noreply.github.com>
    description: JWT-based Authentication Proxy
    formats:
      - apk
      - deb
    bindir: /usr/bin
    contents:
      - src: "systemd/jwt-auth-proxy.service"
        dst: "/lib/systemd/system/jwt-auth-proxy.service"
    overrides:
      deb:
        scripts:
          preinstall: "nfpms/pre-install.sh"
          postinstall: "nfpms/post-install.sh"
          preremove: "nfpms/pre-remove.sh"
          postremove: "nfpms/post-remove.sh"
